db.driverClassName = org.postgresql.Driver
db.url = jdbc:postgresql://localhost:5432/web
db.username = REDACTED
db.password = REDACTED
email.name=REDACTED
email.password=REDACTED
site.url=http://localhost:8080/web
